<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>False</IsPackable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>True</UseWindowsForms>
    <UseWpf>True</UseWpf>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Abstractions" Version="10.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="ReactiveUI" Version="24.1.0" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.TestingHelpers" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gripe.Analyzer\Gripe.Analyzer.csproj">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
