// Copyright (c) 2019 DHGMS Solutions and Contributors. All rights reserved.
// This file is licensed to you under the MIT license.
// See the LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Gripe.SourceGenerator
{
    /// <summary>
    /// Source generator to integrate analyzers into the dotnet tool.
    /// </summary>
    public sealed class DiagnosticCollectionFactoryGenerator : IIncrementalGenerator
    {
        /// <inheritdoc/>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var trigger = context.CompilationProvider;

            context.RegisterSourceOutput(trigger, static (spc, compilation) => Execute(spc, compilation));
        }

        private static void Execute(SourceProductionContext spc, Compilation compilation)
        {
            var compilationReferences = compilation.References;
            var compilationReferenceArray = compilationReferences.ToImmutableArray();
            var analyzerRef = compilationReferenceArray.FirstOrDefault(x =>
                x.Display is "Dhgms.GripeWithRoslynAnalyzer");

            if (analyzerRef == null)
            {
                    return;
            }

            // Resolve the DiagnosticAnalyzer base type symbol.
            var diagnosticAnalyzerSymbol = compilation.GetTypeByMetadataName("Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer");
            if (diagnosticAnalyzerSymbol == null)
            {
                // If Roslyn analyzer types aren't available in this compilation, nothing to do.
                return;
            }

            // Find all public named types that inherit from DiagnosticAnalyzer.
            var found = FindPublicDiagnosticAnalyzers(compilation, diagnosticAnalyzerSymbol);

            // Build a simple generated file that lists the discovered analyzers in a comment.
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("// This file was generated by Gripe.SourceGenerator.DiagnosticCollectionFactoryGenerator.");
            sb.AppendLine("// The following public types inheriting from Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer");
            sb.AppendLine("// were discovered in the compilation references that included \"Dhgms.GripeWithRoslynAnalyzer\":");
            sb.AppendLine();

            if (found.Length == 0)
            {
                sb.AppendLine("// No public DiagnosticAnalyzer-derived types were found.");
            }
            else
            {
                foreach (var f in found)
                {
                    var fq = f.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    if (fq.StartsWith("global::", StringComparison.Ordinal))
                    {
                        fq = fq.Substring("global::".Length);
                    }

                    sb.AppendLine("// - " + fq);
                }
            }

            sb.AppendLine();
            sb.AppendLine("// End of generated list.");

            var sourceText = SourceText.From(sb.ToString(), Encoding.UTF8);
            spc.AddSource("DiagnosticAnalyzerCollection.g.cs", sourceText);
        }

        private static ImmutableArray<INamedTypeSymbol> FindPublicDiagnosticAnalyzers(Compilation compilation, INamedTypeSymbol diagnosticAnalyzerSymbol)
        {
            var results = new List<INamedTypeSymbol>();

            ProcessNamespace(compilation.GlobalNamespace, diagnosticAnalyzerSymbol, results);

            return results.ToImmutableArray();
        }

        private static void ProcessNamespace(INamespaceSymbol ns, INamedTypeSymbol diagnosticAnalyzerSymbol, IList<INamedTypeSymbol> results)
        {
            foreach (var member in ns.GetMembers())
            {
                if (member is INamespaceSymbol childNs)
                {
                    ProcessNamespace(childNs, diagnosticAnalyzerSymbol, results);
                }
                else if (member is INamedTypeSymbol namedType)
                {
                    ProcessNamedType(namedType, diagnosticAnalyzerSymbol, results);
                }
            }
        }

        private static void ProcessNamedType(INamedTypeSymbol namedType, INamedTypeSymbol diagnosticAnalyzerSymbol, IList<INamedTypeSymbol> results)
        {
            // Check declared accessibility is public.
            if (namedType.DeclaredAccessibility == Accessibility.Public)
            {
                if (InheritsFrom(namedType, diagnosticAnalyzerSymbol))
                {
                    results.Add(namedType);
                }
            }

            // Recurse into nested types.
            foreach (var nested in namedType.GetTypeMembers())
            {
                ProcessNamedType(nested, diagnosticAnalyzerSymbol, results);
            }
        }

        private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
        {
            var current = symbol.BaseType;
            while (current != null)
            {
                if (SymbolEqualityComparer.Default.Equals(current, baseType))
                {
                    return true;
                }

                current = current.BaseType;
            }

            return false;
        }
    }
}